sudo: required
dist: trusty
jdk:
- oraclejdk8
env:
  global:
  - JAVA_LIBRARY_PATH=/usr/lib/jni

  #needed to avoid a bug in the hdf5 installer 
  - PS1=">"

  #limit gradle jvm memory usage
  - GRADLE_OPTS=-Xmx512m

  # If this changes, you will need to update the gradle build
  - HDF5_DIR=/hdf/

  #gradle needs this
  - TERM=dumb
  #limit gradle jvm memory
  - GRADLE_OPTS=-Xmx1024m
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_install:
# Grab the HDF5 2.9 (64-bit) binary and install it.
#  shared libs are in /hdf5/HDFView/lib/linux/
#  jars are in /hdf5/HDFView/lib/
# symlinks are made to the JAVA_LIBRARY_PATH
- sudo mkdir -p ${HDF5_DIR}
- echo HDF5 being downloaded and installed in ${HDF5_DIR}
- sudo wget "https://www.hdfgroup.org/ftp/HDF5/releases/HDF-JAVA/hdf-java-2.9/hdfview/hdfview_install_linux64.bin" -O ${HDF5_DIR}/hdfview_install_linux64.bin
- sudo chmod +x ${HDF5_DIR}/hdfview_install_linux64.bin
- sudo ${HDF5_DIR}/hdfview_install_linux64.bin
- sudo mkdir -p ${JAVA_LIBRARY_PATH}
- sudo ln -s ${HDF5_DIR}/HDFView/lib/linux/libjhdf5.so ${JAVA_LIBRARY_PATH}/libjhdf5.so
- sudo ln -s ${HDF5_DIR}/HDFView/lib/linux/libjhdf5.settings ${JAVA_LIBRARY_PATH}/libjhdf5.settings
- sudo chmod -R a+rx ${JAVA_LIBRARY_PATH}
- sudo chmod -R a+rx ${HDF5_DIR}
- ls -la ${HDF5_DIR}/HDFView/lib
- ls -la ${HDF5_DIR}/HDFView/lib/linux
- ls -la ${JAVA_LIBRARY_PATH}

script:
- ./gradlew jacocoTestReport;
after_success:
-  ./gradlew coveralls;
after_failure:
- dmesg | tail -100
